from tkinter import *
w = Tk()
w.geometry("700x300")
w.title("Find  & Replace")

l1 = Label(w,text = "Find:")
l2 = Label(w,text = "Replace:")
l3 = Label(w,text = "Direction:")
b1 = Button(w,text = "Find",width = 8,command = exit)
b2 = Button(w,text = "Find All", width = 8, command = exit)
b3 = Button(w,text = "Replace", width = 8, command = exit)
b4 = Button(w,text = "Replace All", width = 8, command = exit)
e1 = Entry(w, width = 40)
e2 = Entry(w, width = 40)
sb1 = Checkbutton(w,text = "Match whole word only")
sb2 = Checkbutton(w,text = "Match case")
sb3 = Checkbutton(w,text = "Wrap around")
rb1 = Radiobutton(w,text = "Up", value = 0)
rb2 = Radiobutton(w,text = "Down",value = 0)
empty = Label(w,text = " ")
photo = PhotoImage(file = "shrek2.png")
shrek = Label(w,image = photo)
shrek.grid(row = 5, column = 3)
l1.grid(row = 0, column = 0, sticky = W)
l2.grid(row = 1, column = 0, sticky = W)
e1.grid(row = 0, column = 1, columnspan = 3, sticky = E)
e2.grid(row = 1, column = 1, columnspan = 3, sticky = E)
sb1.grid(row = 2, column = 0, sticky = W, columnspan = 2)
sb2.grid(row = 3, column = 0, sticky = W, columnspan = 2)
sb3.grid(row = 4, column = 0, sticky = W, columnspan = 2)
l3.grid(row = 2, column = 2)
rb1.grid(row = 3, column = 2)
rb2.grid(row = 3, column = 3)
empty.grid(row = 0, column = 4)
b1.grid(row = 0, column = 5)
b2.grid(row = 1, column = 5)
b3.grid(row = 2, column = 5)
b4.grid(row = 3, column = 5)
w.mainloop()
